name: manazel
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:

  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.8
  dio: ^5.4.3
  dotted_border: ^2.1.0
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  file_picker: ^8.0.5
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_colorpicker: ^1.1.0
  dropdown_search: ^5.0.6
  flutter_local_notifications: ^17.1.2
  flutter_offline: ^3.0.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  share_plus: ^11.0.0
  fluttertoast: ^8.2.9
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  intl: 0.19.0
  lottie: ^3.1.2
  multiple_result: ^5.1.0
  path: ^1.9.1
  path_provider: ^2.1.3
  photo_view: ^0.15.0
  pinput: ^5.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  skeletonizer: ^1.4.2
  sliver_tools: ^0.2.12
  url_launcher: ^6.3.0
  watcher: ^1.1.0
  pin_code_fields: ^8.0.1
  video_player: ^2.7.0
  auto_size_text: ^3.0.0

dev_dependencies:
  build_runner: null
  flutter_gen_runner: null
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/png/
    - assets/gif/
    - assets/fonts/
    - assets/lottie/
    - assets/translations/

  fonts:
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria-Black.ttf
        - asset: assets/fonts/Alexandria-Medium.ttf
        - asset: assets/fonts/Alexandria-Bold.ttf
        - asset: assets/fonts/Alexandria-ExtraBold.ttf
        - asset: assets/fonts/Alexandria-ExtraLight.ttf
        - asset: assets/fonts/Alexandria-Light.ttf
        - asset: assets/fonts/Alexandria-Medium.ttf
        - asset: assets/fonts/Alexandria-Regular.ttf
        - asset: assets/fonts/Alexandria-SemiBold.ttf


flutter_gen:
  output: lib/src/config/res/
  line_length: 80
  integrations:
    lottie: true
    image: true
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      class_name: AppAssets





